export { default as C404 } from './404'
export { default as About } from './about'
export { default as Contact } from './contact'
export { default as Error } from './error'
export { default as Loading } from './loading'
export { default as NotFound } from './notFound'
export { default as Profile } from './profile'
