export { default as Algolia1 } from './algolia1'
export { default as Algolia2 } from './algolia2'
export { default as Todo } from './todo'
export { default as NewsApi } from './newsapi'
export { default as Clock } from './clock'
export { default as Counter } from './counter'
